jobs = {
    # Order : focal,compare,stopwords,delimiters,maxcost
#    'raw_freq' : ('all_chars', 'dummy_set', 'stopwords', 'delimiters', 10),
#    'ditian_stoptest' : ('reduced_gods', 'dummy_set', 'stopwords', 'delimiters', 10),
'job1' 	: ('reduced_deity', 'reduced_reward', 'stopwords', 'delimiters', 10),
'job2' 	: ('reduced_gods', 'reduced_punishment', 'stopwords', 'delimiters', 10),
'job3' 	: ('reduced_gods', 'reduced_reward', 'stopwords', 'delimiters', 10),
'job4' 	: ('reduced_deity', 'ubc_morality', 'stopwords', 'delimiters', 10),
'job5' 	: ('reduced_deity', 'ubc_emotion', 'stopwords', 'delimiters', 10),
'job6' 	: ('reduced_deity', 'ubc_cognition', 'stopwords', 'delimiters', 10),
'job7' 	: ('reduced_deity', 'ubc_religion', 'stopwords', 'delimiters', 10),
'job8' 	: ('reduced_gods', 'ubc_morality', 'stopwords', 'delimiters', 10),
'job9' 	: ('reduced_gods', 'ubc_emotion', 'stopwords', 'delimiters', 10),
'job10' : ('reduced_gods', 'ubc_cognition', 'stopwords', 'delimiters', 10),
'job11' : ('reduced_gods', 'ubc_religion', 'stopwords', 'delimiters', 10),
'job12' : ('reduced_deity', 'reduced_punishment', 'stopwords', 'delimiters', 10),

'job13' : ('stoplisted_di', 'reduced_reward', 'stopwords', 'delimiters', 10),
'job14' : ('stoplisted_tian', 'reduced_punishment', 'stopwords', 'delimiters', 10),
'job15' : ('stoplisted_tian', 'reduced_reward', 'stopwords', 'delimiters', 10),
'job16' : ('stoplisted_di', 'ubc_morality', 'stopwords', 'delimiters', 10),
'job17' : ('stoplisted_di', 'ubc_emotion', 'stopwords', 'delimiters', 10),
'job18' : ('stoplisted_di', 'ubc_cognition', 'stopwords', 'delimiters', 10),
'job19' : ('stoplisted_di', 'ubc_religion', 'stopwords', 'delimiters', 10),
'job20' : ('stoplisted_tian', 'ubc_morality', 'stopwords', 'delimiters', 10),
'job21' : ('stoplisted_tian', 'ubc_emotion', 'stopwords', 'delimiters', 10),
'job22' : ('stoplisted_tian', 'ubc_cognition', 'stopwords', 'delimiters', 10),
'job23' : ('stoplisted_tian', 'ubc_religion', 'stopwords', 'delimiters', 10),
'job24' : ('stoplisted_di', 'reduced_punishment', 'stopwords', 'delimiters', 10),

'job25' : ('standalone_di', 'reduced_reward', 'stopwords', 'delimiters', 10),
'job26' : ('standalone_tian', 'reduced_punishment', 'stopwords', 'delimiters', 10),
'job27' : ('standalone_tian', 'reduced_reward', 'stopwords', 'delimiters', 10),
'job28' : ('standalone_di', 'ubc_morality', 'stopwords', 'delimiters', 10),
'job29' : ('standalone_di', 'ubc_emotion', 'stopwords', 'delimiters', 10),
'job30' : ('standalone_di', 'ubc_cognition', 'stopwords', 'delimiters', 10),
'job31' : ('standalone_di', 'ubc_religion', 'stopwords', 'delimiters', 10),
'job32' : ('standalone_tian', 'ubc_morality', 'stopwords', 'delimiters', 10),
'job33' : ('standalone_tian', 'ubc_emotion', 'stopwords', 'delimiters', 10),
'job34' : ('standalone_tian', 'ubc_cognition', 'stopwords', 'delimiters', 10),
'job35' : ('standalone_tian', 'ubc_religion', 'stopwords', 'delimiters', 10),
'job36' : ('standalone_di', 'reduced_punishment', 'stopwords', 'delimiters', 10),

}